import { useState } from 'react'
import PageHero from './PageHero'

const initial = { name: '', email: '', subject: '', category: '', message: '' }
export default function Contact() {
  const [fields, setFields] = useState(initial); const [errors, setErrors] = useState({}); const [sent, setSent] = useState(false)
  const change = e => setFields({ ...fields, [e.target.name]: e.target.value })
  const submit = e => { e.preventDefault(); const next = {}; if (!fields.name.trim()) next.name = 'Tell us your name.'; if (!/^\S+@\S+\.\S+$/.test(fields.email)) next.email = 'Enter a valid email address.'; if (!fields.subject.trim()) next.subject = 'Add a subject.'; if (!fields.category) next.category = 'Select a category.'; if (fields.message.trim().length < 20) next.message = 'Your message needs at least 20 characters.'; setErrors(next); if (!Object.keys(next).length) setSent(true) }
  if (sent) return <main><PageHero label="MESSAGE RECEIVED" title={<>THANK<br /><em>YOU.</em></>} copy="This is a simulated submission—no data has been sent. We appreciate you exploring the work." visual="blackops"><button className="button button-red" onClick={() => { setSent(false); setFields(initial) }}>SEND ANOTHER</button></PageHero></main>
  return <main><PageHero label="CONTACT / 06" title={<>START A<br /><em>CONVERSATION.</em></>} copy="Have a project, idea or opportunity worth making? Let’s talk." visual="sekiro" /><section className="contact-section section-pad"><aside><p className="eyebrow">CONTACT CHANNELS</p><h2>LET’S MAKE<br /><em>IT REAL.</em></h2><p><b>GENERAL INQUIRIES</b>hello@example.com</p><p><b>PARTNERSHIPS</b>partners@example.com</p><p><b>PRESS</b>press@example.com</p><p><b>CAREERS</b>careers@example.com</p></aside><form noValidate onSubmit={submit}><label>Name<input name="name" value={fields.name} onChange={change} aria-invalid={!!errors.name} aria-describedby="name-error" /></label>{errors.name && <p id="name-error" className="form-error" role="alert">{errors.name}</p>}<label>Email<input name="email" type="email" value={fields.email} onChange={change} aria-invalid={!!errors.email} aria-describedby="email-error" /></label>{errors.email && <p id="email-error" className="form-error" role="alert">{errors.email}</p>}<label>Subject<input name="subject" value={fields.subject} onChange={change} aria-invalid={!!errors.subject} /></label>{errors.subject && <p className="form-error" role="alert">{errors.subject}</p>}<label>Category<select name="category" value={fields.category} onChange={change} aria-invalid={!!errors.category}><option value="">Select a category</option><option>General inquiry</option><option>Partnership</option><option>Press</option><option>Careers</option></select></label>{errors.category && <p className="form-error" role="alert">{errors.category}</p>}<label>Message<textarea name="message" rows="5" value={fields.message} onChange={change} aria-invalid={!!errors.message} /></label>{errors.message && <p className="form-error" role="alert">{errors.message}</p>}<button className="button button-red" type="submit">SEND MESSAGE <i>↗</i></button></form></section></main>
}
