import { Link } from 'react-router-dom'
import { motion, useScroll, useTransform } from 'framer-motion'
import { FiArrowDownRight, FiPlay } from 'react-icons/fi'
import VideoHero, { VideoSection } from '../components/media/VideoHero'
import SectionIntro from '../components/SectionIntro'
import GameCard from '../components/GameCard'
import { games } from '../data/games'

export default function Home() {
  const { scrollY } = useScroll(); const y = useTransform(scrollY, [0, 700], [0, 130])
  return <main>
    <VideoHero className="home-hero"><motion.div className="hero-content" style={{ y }} initial="hidden" animate="show"><motion.p className="eyebrow" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .25 }}>INDEPENDENT CREATIVE STUDY / 2026</motion.p><motion.h1 initial={{ opacity: 0, y: 38 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .35, duration: .9 }}>WE CREATE<br /><em>THE FUTURE</em> OF PLAY.</motion.h1><motion.p className="hero-copy" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .55, duration: .65 }}>Building unforgettable worlds, characters and experiences for players everywhere.</motion.p><motion.div className="hero-actions" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .72 }}><Link className="button button-red" to="/games">EXPLORE GAMES <FiArrowDownRight /></Link><Link className="button button-ghost" to="/studio">DISCOVER THE STUDIO</Link></motion.div></motion.div><div className="hero-scroll"><span>SCROLL TO EXPLORE</span><i /></div><div className="hero-index">01 <span>/</span> 06</div></VideoHero>
    <section className="statement section-pad"><div className="statement-meta"><p className="eyebrow">A PORTFOLIO IN MOTION</p><span>01 / 04</span></div><motion.div initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .9 }}><h2>THE BEST EXPERIENCES<br />ARE BUILT <em>TO BE FELT.</em></h2><p>We explore the intersection of purposeful systems, dramatic visual language, and clear human interaction. Every moment earns its place.</p><Link className="text-link" to="/projects">VIEW SELECTED WORK <i>↗</i></Link></motion.div></section>
    <section className="featured-game"><VideoSection visual="blackops"><div className="featured-game-copy"><p className="eyebrow">FEATURED WORLD / 2026</p><h2>CALL OF<br /><em>DUTY</em></h2><p className="feature-tagline">THE NEXT GENERATION OF COMBAT.</p><div className="game-meta"><span>FPS</span><span>PC · CONSOLE</span><span>ONGOING</span></div><p>A focused, original interface exploration imagining high-stakes tactical play and cinematic tension.</p><div className="hero-actions"><Link className="button button-red" to="/games/call-of-duty">EXPLORE GAME</Link><button className="button button-ghost" type="button" aria-label="Watch Call of Duty cinematic trailer placeholder"><FiPlay /> WATCH TRAILER</button></div></div><div className="corner-copy">ORIGINAL GENERATED MEDIA<br />NO OFFICIAL MEDIA INCLUDED</div></VideoSection></section>
    <section className="games-preview section-pad"><SectionIntro eyebrow="SELECTED FRANCHISE STUDIES" title={<>DESIGNED FOR<br /><em>THE MOMENT.</em></>} copy="A collection of original visual studies inspired by the distinct energy of legendary game worlds." /><div className="game-grid">{games.slice(0, 3).map((game, index) => <GameCard key={game.slug} game={game} index={index} />)}</div><Link className="button button-outline center-button" to="/games">VIEW ALL GAMES <FiArrowDownRight /></Link></section>
    <section className="split-callout"><div className="visual visual-sekiro" /><div><p className="eyebrow">CREATIVE TECHNOLOGY</p><h2>THE CRAFT<br />BEHIND <em>THE IMPACT.</em></h2><p>From interaction design to responsive interfaces, the tools stay quiet so the experience can speak.</p><Link className="text-link" to="/studio">OUR APPROACH <i>↗</i></Link></div></section>
    <section className="news-strip"><p className="eyebrow">FROM THE FIELD</p><Link to="/news"><span>NEW /</span> BUILDING FOR PRESENCE, NOT NOISE <i>↗</i></Link></section>
  </main>
}
